# ----------- CONFIGURABLE START -----------
title:            "Nuredin Ali"
description:      "Such theme, very cool."
url:              https://nuredinabd.github.io/home/ # Site url, without a slash at the end.
signoff:          "Nuredin Ali" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Posts
    url:          /about
    external:     false
  - name:         About me
    url:          /
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"